config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books

  root 'books#index'
  get 'users/payed', to: "users#pay", as: "payed" 
  patch 'users/payed', to: "users#remove", as: "remove"
  post 'books/:id', to: "books#status", as: "status"
  get 'users/:id', to: "users#profile", as: "profile" 
  put 'users/:id', to: "users#reserve", as: "reserve"
  get 'buys/:id', to: "buys#pay", as: "pay"
  post 'buys/:id', to: "buys#buy", as: "buy"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user, optional: true
    enum status: [:available, :reserved, :payed]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy status ]
  before_action :authenticate_user!

  # GET /books or /books.json
  def index
    @books = Book.all
    @book = Book.new

  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
    
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)
    @book.status = 0
    respond_to do |format|
      if @book.save
        format.js {redirect_to root_path, notice: "Book was successfully created."}
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def status
    respond_to do |format|
      if @book.update(user: current_user, status: 1)
        @books = Book.all
        format.js { render nothing: true, notice: "Book was successfully reserved." }
        format.html { redirect_to @book, notice: "Book was successfully reserved." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :status)
    end
end

app/controllers/buys_controller.rb
class BuysController < ApplicationController
    def pay
        @book = Book.find(params[:id])
       
    end

    def buy
        @user = current_user
        @book = Book.find(params[:id])
        respond_to do |format|
          if @book.update( status: 2)
            # format.js { render nothing: true, notice: "Book was successfully bought." }
            format.html { redirect_to profile_path, notice: "Book was successfully bought." }
            format.json { render :show, status: :ok, location: @book }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @book.errors, status: :unprocessable_entity }
          end
        end 
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    def profile
        @user = current_user
        @books = @user.books.where(status: 1)
        
    end

    def pay
      @user = current_user
      @books = @user.books.where(status: 2)
    end

  #   def available
  #     @user = current_user
  #     @books = @user.books.where(status: 0)
  # end
    
    def reserve
        @user = current_user
        @book = Book.find(params[:id])
        respond_to do |format|
          if @book.update(user: nil, status: 0)
            @books = @user.books.where(status: 1)
            format.js { render nothing: true, notice: "Book was successfully reserverd." }
            format.html { redirect_to @book, notice: "Book was successfully updated." }
            format.json { render :show, status: :ok, location: @book }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @book.errors, status: :unprocessable_entity }
          end
        end
    end

  def remove
    @user = current_user
        @book = Book.find(params[:id])
        respond_to do |format|
          if @book.update(status: 0)
           
            format.html { redirect_to @book, notice: "Book was successfully updated." }
            format.json { render :show, status: :ok, location: @book }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @book.errors, status: :unprocessable_entity }
          end
        end
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, remote: true, :format => 'js') do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>
  
  <div class="actions">
    <%= form.submit data: {disable_with: "Your request is being processed..."} %>
  </div>
<% end %>

app/views/books/_index.html.erb
<% @books.each do |book| %>
  <%if book.status == 'available' %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.status %></td>
      
        <td><%= link_to 'Show', book, remote: true %></td>
        <td><%= link_to 'Reserve', status_path(book), method: :post, remote: true %></td>
      </tr>
  <% end %>
<% end %>

app/views/books/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Status:</strong>
  <%= @book.status %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/books/create.js.erb
$(​'#bookList'​).append(​ "<%= escape_javascript(render @book, locals: { book: @book} ) %>"​ );

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<div id="book_show"></div>
<div>
  <h2>Request a book</h2>
  <span>The books requested have a 24-hour time to be available in our store</span>
  <div></div><%= render 'form', book: @book %>
</div>


<br>
<table class = "table">
  <thead class="thead-dark">
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id='bookList'>
     <%= render 'index' %>
  </tbody>
</table>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.js.erb
$("#bookShow").append("<%= escape_javascript(render partial: 'books/show', locals: { book: @book } ) %>")

app/views/books/status.js.erb
console.log('test')
$('#bookList').html('<%= escape_javascript(render partial: "index")%>')
console.log('test2')

app/views/buys/pay.html.erb
<%= form_with(model: @book, local: true, url: "/buys/#{@book.id}", method: :post )do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% @book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <span id="message">Form will lock in </span>
    <span id="minutes"></span>:<span id="seconds"></span>
  </div>

  
  <div class="field">
    <%= form.label :title %>
    <%= @book.title %>
  </div>


  <div class="actions">
    <%= form.submit "Buy" %>
  </div>
<% end %>

<%= link_to 'Back', profile_path %>

app/views/buys/pay.js.erb
function displayTimer (miliseconds) {
  let end = miliseconds / 1000 ;
  let min = $("#minutes")[0];
  let sec = $("#seconds")[0];
  if (end > 0 ) {
    let ticker = setInterval( function (){
    end--;
    if (end <= 0 ) { 
      clearInterval(ticker); 
      disablePay(); }
    let secs = end;
    let mins = Math.floor(secs / 60 ); 
    secs -= mins * 60 ;
    min.innerHTML = ( "00" + mins).slice( -2 );
    sec.innerHTML = ( "00" + secs).slice( -2 );
    }, 1000);
  }
}

function disablePay() {
  $(".pay").prop('disabled', true);
  $.ajax({
    url: "<%= unbook_path(@book) %>", 
    type: "POST",
    dataType: 'script',
    data: { book: "<%= @book %>"}
  });
};

displayTimer(120000)
$("#show").html("<%= escape_javascript ( render partial: 'show')%>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="container">
      <%= yield %>
    </div>

    
    <script src="http://code.jquery.com/jquery-3.4.1.min.js"></script>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-sm  sticky-top navbar-dark py-4" style="background-color: #76448A;">
    <div class="mx-auto d-sm-flex d-block flex-sm-nowrap">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample11" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarsExample11">
            <ul class="navbar-nav">
              <% if current_user %>
                <li class="nav-item">  <%= link_to 'Home', root_path, class:"nav-link" %></li>
                <li class="nav-item">  <%= link_to 'Profile', profile_path(current_user), class:"nav-link" %></li>
                <li class="nav-item">  <%= link_to 'My orders', payed_path(current_user), class:"nav-link" %></li>
                <li class="nav-item">  <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:"nav-link" %></li>
              <% else %>
                <li class="nav-item">  <%= link_to 'Log in', new_user_session_path, class:"nav-link" %></li>
                <li class="nav-item">  <%= link_to 'Sign in', new_user_registration_path, class:"nav-link" %></li>
              <% end %>
            </ul>
        </div>
    </div>
    
</nav>

app/views/users/ availabled.html.erb
<p id="notice"><%= notice %></p>

<h1>My Profile</h1>
<h2>Hi <%= @current_user.email %>!</h2>

<div id="bookShow"></div>

<table class="table">
  <thead class ="thead-light">
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id='bookList'>
    <%= render 'available', books: @books %>
  </tbody>
</table>

app/views/users/_available.html.erb
<% @books.each do |book| %>
  <%if book.status == 'available' %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.status %></td>
      
        <td><%= link_to 'Show', book, remote: true %></td>
        <td><%= link_to 'Reserve', status_path(book), method: :post, remote: true %></td>
      </tr>
  <% end %>
<% end %>

app/views/users/_index.html.erb
<% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.author %></td>
    <td><%= book.status %></td>
    <td><%= link_to 'Show', book, remote: true %></td>
    <td><%= link_to 'Pay', "/buys/#{book.id}" %></td>
    <td><%= link_to 'Destroy', reserve_path(book), method: :put, remote: true%></td>
    
  </tr>
<% end %>

app/views/users/_payed.html.erb
<% @books.each do |book| %>
  <%if book.status == 'payed' %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.status %></td>
      
        <td><%= link_to 'Show', book, remote: true %></td>
        <td><%= link_to 'Remove', remove_path(book), method: :patch, remote: true %></td>
        <!-- <td><%= link_to 'Destroy', reserve_path(book), method: :put, remote: true%></td> -->
      </tr>
  <% end %>
<% end %>

app/views/users/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Status:</strong>
  <%= @book.status %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/users/pay.html.erb
<p id="notice"><%= notice %></p>

<h1>My Profile</h1>
<h2>Hi <%= @current_user.email %>!</h2>

<div id="bookShow"></div>

<table class="table">
  <thead class ="thead-light">
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id='bookList'>
    <%= render 'payed', books: @books %>
  </tbody>
</table>

app/views/users/profile.html.erb
<p id="notice"><%= notice %></p>

<h1>My Profile</h1>
<h2>Hi <%= @current_user.email %>!</h2>

<div id="bookShow"></div>

<table class="table">
  <thead class ="thead-light">
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id='bookList'>
    <%= render 'index', books: @books %>
  </tbody>
</table>

app/views/users/reserve.js.erb
console.log('test')
$('#bookList').html('<%= escape_javascript(render partial: "index")%>')
console.log('test2')

app/views/users/show.js.erb
$("#bookShow").append("<%= escape_javascript(render partial: 'users/show', locals: { book: @book } ) %>")